trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/*.xml'
      goals: 'clean test'
      options: '-Dsurefire.suiteXmlFiles=src/test/config/MultipleTest.xml'
      continueOnError: true
    env:
      BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
      BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)
      BROWSERSTACK_PROJECT:  $(BROWSERSTACK_PROJECT)
      BROWSERSTACK_BUILD: $(BROWSERSTACK_BUILD)
      BROWSERSTACK_NAME: $(BROWSERSTACK_NAME)

  - task: CopyFiles@2
    condition: always()
    inputs:
      contents: 'target/surefire-reports/junitreports/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'JUnitReports'
      publishLocation: 'Container'